// <auto-generated />
namespace SIMOV_WS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddedResponsavelPaciente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedResponsavelPaciente));
        
        string IMigrationMetadata.Id
        {
            get { return "201411291503386_AddedResponsavelPaciente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
